### ISSUE TITLE
'K01' not found

### ISSUE THREAD

**Issue by markusloecher** [Servane-Gey/Spatial-classification-trees#1]
In Simulation.study.R please fix:

ggplot(K01, aes(x = r, y = difference)) : 
  Object 'K01' not found

It would be great if that file worked "as is".
Thanks!

**Comment by Servane-Gey** [comment]
Dear Pr Loecher,

I apologize for this error in the simulation file, due to an omission when
I updated files on Github.

The file has been corrected and reloaded.

Thank you for alerting me to this error.

Best Regards,


*Servane Gey*

*Maître de Conférences*

*Département STatistique et Informatique Décisionnelle*



IUT DE PARIS

143 avenue de Versailles - 75016 Paris

Tél : 01 76 53 48 21


Laboratoire MAP5

45 rue des Saints Pères - 75270 Paris Cedex 06

Tél : 01 76 53 03 70


*Page web <http://www.math-info.univ-paris5.fr/~gey/>*







Le ven. 11 déc. 2020 à 11:14, Markus Loecher <notifications@github.com> a
écrit :
